### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by x13machine** [ethereumjs/ethrpc#43]
### Error:
```
/home/brandan/node_modules/ethrpc/src/rpc/submit-request-to-blockchain.js:47
    internalState.get("transporter").blockchainRpc(jso, transportRequirements, debug.broadcast);
                                    ^
 
TypeError: Cannot read property 'blockchainRpc' of null
    at /home/brandan/node_modules/ethrpc/src/rpc/submit-request-to-blockchain.js:47:37
    at store.dispatch (/home/brandan/node_modules/redux-thunk-subscribe/src/index.js:10:18)
    at /home/brandan/node_modules/ethrpc/src/wrappers/raw.js:10:12
    at store.dispatch (/home/brandan/node_modules/redux-thunk-subscribe/src/index.js:10:18)
    at /home/brandan/node_modules/ethrpc/src/wrappers/make-wrapper.js:12:14
    at store.dispatch (/home/brandan/node_modules/redux-thunk-subscribe/src/index.js:10:18)
    at /home/brandan/node_modules/ethrpc/src/transact/call-or-send-transaction.js:31:14
    at store.dispatch (/home/brandan/node_modules/redux-thunk-subscribe/src/index.js:10:18)
    at Object.callOrSendTransaction (/home/brandan/node_modules/ethrpc/src/create-ethrpc.js:240:66)
    at Object.<anonymous> (/home/brandan/grava/tests/ethrpc.js:11:17)
```

### Code:

```
var rpc = require("ethrpc");
 
rpc.connect({
    httpAddresses: ["http://localhost:9545"],
    wsAddresses: [],
    ipcAddresses: []
}, function (err) {
    console.log(err)
});
 
console.log(rpc.callOrSendTransaction({
    to: '0xfb88de099e13c3ed21f80a7a1e49f8caecf10df6',
    name: 'getIndex',
    signature: [],
    params: [],
    send: true,
    returns: 'int'
}))
```

**Comment by tinybike** [comment]
It means you're not connected to the Ethereum node.  We really need to improve ethrpc's error messaging.  Try putting your callOrSendTransaction into connect's call back and see if that fixes your connection!
